### ISSUE TITLE
When using router with hashbang authentication event is not fired

### ISSUE THREAD

**Issue by cristiandouce** [auth0/auth0-vue#12]
From auth0/lock/issues/622

---
### Authenticated event not fired for Webpack, Vue, Vue-Router

I can not get the authenticated event to fire when using Webpack 1.13.2, Vue 1.0.26, Vue-Router 0.7.13 and Auth0-lock 10.3.0. Other's have had similar issues. The sample code provided by Auth0 also does not work. The only code that works is from https://github.com/auth0/auth0-vue.

Below is a sample project that I am using. The source code is under the src directory. If you could please add a client id and domain to src/components/home.vue on line 20 to test.

https://github.com/Uptown76/Auth0VueWebpack

npm install
npm run dev

Thanks
@Uptown76

**Comment by jsoncorwin** [comment]
Auth0-lock [10.10.0](https://github.com/auth0/lock/blob/master/CHANGELOG.md#v10100-2017-01-17) introduced the concept for resumeAuth and autoParseHash which allows the client to handle parsing of the hash manually instead of Lock doing it for you.

Setting autoParseHash to false when instantiating Auth0Lock and then manually reading window.location.hash and passing it to lock.resumeAuth lets you handle the authentication without conflicting with vue-router (just make sure to grab the hash before vue-router takes over).
