### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot destructure property 'loginWithRedirect' of 'useAuth0(...)' as it is undefined.

### ISSUE THREAD

**Issue by radar1975** [auth0/auth0-vue#121]
### Describe the problem you'd like to have solved

I have tested your sample it work fine but when we integrate same thing into our existing Vue.js app, we are always gatting this error
**Uncaught (in promise) TypeError: Cannot destructure property 'loginWithRedirect' of 'useAuth0(...)' as it is undefined.**

### Describe the ideal solution

I know it is maybe an issue in our side but we sincerally need help here to get this going :-(

### Additional context

![image](https://user-images.githubusercontent.com/1986318/168319968-0d2b850e-5516-4f22-98b3-5d1e02bb7a4c.png)

Our code look exactly like in the sample

app.ts
```
  app.use(
    createAuth0({
      domain: 'YOUR DOMAIN',
      client_id: 'YOUR CLIENT ID',
      redirect_uri: window.location.origin,
    })
  )
```

index.vue
```
<template>
    <div>
      <button @click="login">Log in</button>
    </div>
</template>


<script>

import { useAuth0 } from '@auth0/auth0-vue';

export default {
  setup() {
    const { loginWithRedirect } = useAuth0();
    return {
      login: () => {
        loginWithRedirect();
      }
    }
  }  
};

</script>
```

versions
- auth0-vue 1.0.1
- Vue.js 3.2.33

**Comment by frederikprijck** [comment]
Thanks for reaching out!

The code shared here looks fine, so the issue might originate elsewhere.
Would you be able to spot any differences between your application and our sample?

**Comment by weva-io** [comment]
I get an error that – from what I gathered – is similar: `Uncaught TypeError: (intermediate value)() is undefined`. Problem occurs when trying to destructure like this: `const { loginWithRedirect } = useAuth0();`.

Same code setup and Vue + auth0-vue versions as @radar1975 has.

**Comment by radar1975** [comment]
We are using a purchased Vue.js template. The template name is Vuero and can be found here (https://vuero.cssninja.io/) and we have replicate the sample code as is.

Thanks for your help

**Comment by orishoshan** [comment]
Hey @radar1975, I experienced this same warning and the Auth0 SDK didn't work. For me, the cause was having multiple versions of `@vue/runtime-core` in my `package-lock.json` / `yarn.lock`.

Upon debugging, I noticed that Vue.js prints this warn when the application is not initialized within the `inject()` function used by the Auth0 SDK. So I checked to see if the `provide()` call happened successfully, and indeed it was. What happened to the app then? Well, upon taking a closer look (and being confused for a while), I noticed that they weren't the same file! One of the `@vue/runtime-core` files I was looking at was in `@auth0/auth0-vue`'s node_modules, while the other was in my project's. Somehow I'd had two `runtime-core`s, which is where `inject()` and `provide()` are implemented, and somehow `createAuth0` was using one while `useAuth0` was using another.

I suspect this is because with `createAuth0` you provide the auth0 plugin to the app (e.g. `app.use(createAuth0(...))`), while in `useAuth0`, it imports the app independently. So from `useAuth0`'s point of view, which had imported its own version of `@vue/runtime-core`, the app was never initialized.

Unfortunately I don't think there's anything smart Auth0 can do about this, as it seems to be something that perhaps Vue could do to provide a better error message or prevent through a redesign of how they store the app reference, or that package managers could better warn about.

**Comment by radar1975** [comment]
Just to let you know that this issue was resolve by updating the template version. Depending issues like @orishoshan [orishoshan](https://github.com/orishoshan) was saying.

Thanks for your time everyone

**Comment by frederikprijck** [comment]
That's good te hear! Thanks @orishoshan for the elaboration here!

**Comment by gokhantaskan** [comment]
I'm facing the exact error using Nuxt 3 and Auth0-Vue package.

[stackblitz repro link](https://stackblitz.com/edit/nuxt-starter-2hvuzv?file=plugins%2Fauth0.ts)

I also implemented exactly the same into a more complex project, but these are the core authentication codes. How can I solve the 500 error issue. In my local env, when I click to "Return home" button, I can see that auth0 is logged in, and my data is there. When I hit the logout button, it redirects to 500 page again, then shows me the Auth0 page. So, page refreshes and redirections fail.

**Comment by frederikprijck** [comment]
Here is a thread on nuxt, would any of that help u as well ?

https://github.com/auth0/auth0-vue/issues/197

**Comment by gokhantaskan** [comment]
> Here is a thread on nuxt, would any of that help u as well ?
> 
> #197
> 
> Based on my limited Nuxt knowledge (please know we have no explicit support for Nuxt, but happy to fix anything that should help Nuxt support), it looks like u are registering the plugin only when process.client is truthy, but are still trying to destructure it eitherway, which fails.

To utilize the `useAuth0` composable effectively, I needed to encapsulate the components with `ClientOnly` - as you pointed out, because I'm importing it subsequent to the server rendering process. The temporary solution for `auth0-vue` plugin is:

```vue
<ClientOnly>
  <NuxtPage />
</ClientOnly>
```
The rest can stay the same. Wish we could have a good nuxt plugin in the near future.

**Comment by frederikprijck** [comment]
Great it works @gokhantaskan , doesnt look to bad of a workaround if u ask me.

You should be able to also use https://github.com/sidebase/nuxt-auth for integration Auth0 in Nuxt 3.
